### PR TITLE
Attempt to stop the cycle if it's not saved

### PR DESCRIPTION
**Pull request by NerdyChara**
By all accounts this should prevent any changes in the light and day over the course of the gameplay.

### CODE REVIEW

**Comment by AdriLez** [comment]
`&& dayNightSaveNight == true` is technically correct, but it is a little confusing; I propose simply putting `&& dayNightSaveNight` instead, it is more self-explanatory.

**Comment by AdriLez** [comment]
Also, I don't understand something: if someone don't want to use the 'dayNightSaveNight' switch but still want to use the day/night system, the time will never update for him/her.

**Comment by NerdyChara** [comment]
Hmm. That's a very good point. Although this was the fastest solution I could come up with. I want to find a way to permanently disable the day night cycle.

**Comment by NerdyChara** [comment]
I'll go ahead and my own switch for it.

**Comment by AdriLez** [comment]
I think creating an 'initial day speed' parameter will make more sense.
It will allow you to achieve what you want (by putting it at 0), while having a less niche application.

**Comment by AdriLez** [comment]
I made the code, but I don't have the autorisation to post on your repo, so I will do another pull request.

**Pull request merged**
